//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityReferences.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mail.nwsc.co.ug/nwscbillinginterface/nwscbillinginterface.asmx")]
        public string UtilityReferences_NWSC_NWSCBillingInterface {
            get {
                return ((string)(this["UtilityReferences_NWSC_NWSCBillingInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://196.10.228.48/urabnkpmtservice/urapayment.asmx")]
        public string UtilityReferences_URA_UraPmtService {
            get {
                return ((string)(this["UtilityReferences_URA_UraPmtService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://41.84.196.234:4044/umemebillinterface/EPayment.asmx")]
        public string UtilityReferences_UMEME_EPayment {
            get {
                return ((string)(this["UtilityReferences_UMEME_EPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://beta.tamsonline.co.za/kcca-pts/api/telecom-paymentv1.php")]
        public string UtilityReferences_KCCA1_TelecomPaymentService {
            get {
                return ((string)(this["UtilityReferences_KCCA1_TelecomPaymentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8020/StartimesConnect/StarTimesConnect.asmx")]
        public string UtilityReferences_StarTimes_IHaiWaiElectronicPaymentService {
            get {
                return ((string)(this["UtilityReferences_StarTimes_IHaiWaiElectronicPaymentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://196.43.133.113:8001/EpaymentInterface/EPayment.asmx")]
        public string UtilityReferences_Makerere_EPayment {
            get {
                return ((string)(this["UtilityReferences_Makerere_EPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uat.mcadigitalmedia.com/VendorSelfCare/SelfCareService.svc")]
        public string UtilityReferences_DSTVApi_SelfCareService {
            get {
                return ((string)(this["UtilityReferences_DSTVApi_SelfCareService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://196.0.25.194:8007/TestCardlessApi/CardlessMoMoApi.asmx")]
        public string UtilityReferences_PBU_CardlessMoMoApi {
            get {
                return ((string)(this["UtilityReferences_PBU_CardlessMoMoApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://193.108.252.222/ecitie/api/telecom-paymentv1.php")]
        public string UtilityReferences_KCCA_TelecomPaymentService {
            get {
                return ((string)(this["UtilityReferences_KCCA_TelecomPaymentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kyupay.kyu.ac.ug/epay")]
        public string UtilityReferences_KYU_EPayment {
            get {
                return ((string)(this["UtilityReferences_KYU_EPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.3:6048/TestDatabaseApi/Service.asmx")]
        public string UtilityReferences_TestDbApi_Service {
            get {
                return ((string)(this["UtilityReferences_TestDbApi_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8020/SchoolFeesApi/SchoolApi.asmx")]
        public string UtilityReferences_SchoolsApi_SchoolApi {
            get {
                return ((string)(this["UtilityReferences_SchoolsApi_SchoolApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://zee-pay.com/zeepay_v2/bankservice")]
        public string UtilityReferences_NkumbaPayInterface_EPayment {
            get {
                return ((string)(this["UtilityReferences_NkumbaPayInterface_EPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://tpg.tamsonline.co.za/api/exec/PaymentNotificationService/")]
        public string UtilityReferences_Tucksee_PaymentNotificationService {
            get {
                return ((string)(this["UtilityReferences_Tucksee_PaymentNotificationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://197.221.149.74:17300/GatewayServiceASP.asmx")]
        public string UtilityReferences_WenrecoApi_XMLVendService {
            get {
                return ((string)(this["UtilityReferences_WenrecoApi_XMLVendService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://193.108.252.222/ecitie/api/bank-paymentv1.php")]
        public string UtilityReferences_KCCA2_BankPaymentService {
            get {
                return ((string)(this["UtilityReferences_KCCA2_BankPaymentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://196.8.208.145/testleveloneapi/pegpay.asmx")]
        public string UtilityReferences_StanbicCemasApi_PegPay {
            get {
                return ((string)(this["UtilityReferences_StanbicCemasApi_PegPay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.3:5099/LiveDataAccess/DataAccess.asmx")]
        public string UtilityReferences_DataApi_DataAccess {
            get {
                return ((string)(this["UtilityReferences_DataApi_DataAccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://196.8.208.145/pegpay.asmx")]
        public string UtilityReferences_StanbicBankApi_PegPay {
            get {
                return ((string)(this["UtilityReferences_StanbicBankApi_PegPay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8020/MowePaymentsTestApi/MowePaymentApi.asmx")]
        public string UtilityReferences_MoweApi_MowePaymentApi {
            get {
                return ((string)(this["UtilityReferences_MoweApi_MowePaymentApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/broker/mobilemoney/invoice/validation/v1.0")]
        public string UtilityReferences_NDAValidation_MobileMoneyInvoiceServiceService {
            get {
                return ((string)(this["UtilityReferences_NDAValidation_MobileMoneyInvoiceServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/broker/mobilemoney/invoice/payment/v1.0")]
        public string UtilityReferences_NDAPayment_MobileMoneyPaymentServiceService {
            get {
                return ((string)(this["UtilityReferences_NDAPayment_MobileMoneyPaymentServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://192.168.192.124:443/eColSOAPServertest/index.php")]
        public string UtilityReferences_NSSF_NSSFWSDL {
            get {
                return ((string)(this["UtilityReferences_NSSF_NSSFWSDL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://115.238.36.166:10015/xmlvend/xmlvend.wsdl")]
        public string UtilityReferences_SageWood_XMLVendService2_1 {
            get {
                return ((string)(this["UtilityReferences_SageWood_XMLVendService2_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8020/mailerapi/Messenger.asmx")]
        public string UtilityReferences_MailApi_Messenger {
            get {
                return ((string)(this["UtilityReferences_MailApi_Messenger"]));
            }
        }
    }
}
