//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UtilityReferences.KCCA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TelecomPaymentServiceBinding", Namespace="urn:TelecomPaymentService")]
    public partial class TelecomPaymentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyReferenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback transactOperationCompleted;
        
        private System.Threading.SendOrPostCallback closeTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback eodReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TelecomPaymentService() {
            this.Url = global::UtilityReferences.Properties.Settings.Default.UtilityReferences_KCCA_TelecomPaymentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authenticateCompletedEventHandler authenticateCompleted;
        
        /// <remarks/>
        public event verifyReferenceCompletedEventHandler verifyReferenceCompleted;
        
        /// <remarks/>
        public event transactCompletedEventHandler transactCompleted;
        
        /// <remarks/>
        public event closeTransactionCompletedEventHandler closeTransactionCompleted;
        
        /// <remarks/>
        public event eodReportCompletedEventHandler eodReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TelecomPaymentService#authenticate", RequestNamespace="urn:TelecomPaymentService", ResponseNamespace="urn:TelecomPaymentService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string authenticate(string ap_key, string api_username, string api_password, string hash, object backref) {
            object[] results = this.Invoke("authenticate", new object[] {
                        ap_key,
                        api_username,
                        api_password,
                        hash,
                        backref});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void authenticateAsync(string ap_key, string api_username, string api_password, string hash, object backref) {
            this.authenticateAsync(ap_key, api_username, api_password, hash, backref, null);
        }
        
        /// <remarks/>
        public void authenticateAsync(string ap_key, string api_username, string api_password, string hash, object backref, object userState) {
            if ((this.authenticateOperationCompleted == null)) {
                this.authenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthenticateOperationCompleted);
            }
            this.InvokeAsync("authenticate", new object[] {
                        ap_key,
                        api_username,
                        api_password,
                        hash,
                        backref}, this.authenticateOperationCompleted, userState);
        }
        
        private void OnauthenticateOperationCompleted(object arg) {
            if ((this.authenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authenticateCompleted(this, new authenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TelecomPaymentService#verifyReference", RequestNamespace="urn:TelecomPaymentService", ResponseNamespace="urn:TelecomPaymentService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string verifyReference(string session_key, string reference, string hash, string backref) {
            object[] results = this.Invoke("verifyReference", new object[] {
                        session_key,
                        reference,
                        hash,
                        backref});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verifyReferenceAsync(string session_key, string reference, string hash, string backref) {
            this.verifyReferenceAsync(session_key, reference, hash, backref, null);
        }
        
        /// <remarks/>
        public void verifyReferenceAsync(string session_key, string reference, string hash, string backref, object userState) {
            if ((this.verifyReferenceOperationCompleted == null)) {
                this.verifyReferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyReferenceOperationCompleted);
            }
            this.InvokeAsync("verifyReference", new object[] {
                        session_key,
                        reference,
                        hash,
                        backref}, this.verifyReferenceOperationCompleted, userState);
        }
        
        private void OnverifyReferenceOperationCompleted(object arg) {
            if ((this.verifyReferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyReferenceCompleted(this, new verifyReferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TelecomPaymentService#transact", RequestNamespace="urn:TelecomPaymentService", ResponseNamespace="urn:TelecomPaymentService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string transact(string session_key, string reference, object transaction, string hash, string backref) {
            object[] results = this.Invoke("transact", new object[] {
                        session_key,
                        reference,
                        transaction,
                        hash,
                        backref});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transactAsync(string session_key, string reference, object transaction, string hash, string backref) {
            this.transactAsync(session_key, reference, transaction, hash, backref, null);
        }
        
        /// <remarks/>
        public void transactAsync(string session_key, string reference, object transaction, string hash, string backref, object userState) {
            if ((this.transactOperationCompleted == null)) {
                this.transactOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransactOperationCompleted);
            }
            this.InvokeAsync("transact", new object[] {
                        session_key,
                        reference,
                        transaction,
                        hash,
                        backref}, this.transactOperationCompleted, userState);
        }
        
        private void OntransactOperationCompleted(object arg) {
            if ((this.transactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transactCompleted(this, new transactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TelecomPaymentService#closeTransaction", RequestNamespace="urn:TelecomPaymentService", ResponseNamespace="urn:TelecomPaymentService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string closeTransaction(string session_key, string reference, object transaction_id, string hash, string backref) {
            object[] results = this.Invoke("closeTransaction", new object[] {
                        session_key,
                        reference,
                        transaction_id,
                        hash,
                        backref});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void closeTransactionAsync(string session_key, string reference, object transaction_id, string hash, string backref) {
            this.closeTransactionAsync(session_key, reference, transaction_id, hash, backref, null);
        }
        
        /// <remarks/>
        public void closeTransactionAsync(string session_key, string reference, object transaction_id, string hash, string backref, object userState) {
            if ((this.closeTransactionOperationCompleted == null)) {
                this.closeTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncloseTransactionOperationCompleted);
            }
            this.InvokeAsync("closeTransaction", new object[] {
                        session_key,
                        reference,
                        transaction_id,
                        hash,
                        backref}, this.closeTransactionOperationCompleted, userState);
        }
        
        private void OncloseTransactionOperationCompleted(object arg) {
            if ((this.closeTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.closeTransactionCompleted(this, new closeTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BankPaymentService#eodReport", RequestNamespace="urn:BankPaymentService", ResponseNamespace="urn:BankPaymentService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string eodReport(string session_key, string content, string backref) {
            object[] results = this.Invoke("eodReport", new object[] {
                        session_key,
                        content,
                        backref});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eodReportAsync(string session_key, string content, string backref) {
            this.eodReportAsync(session_key, content, backref, null);
        }
        
        /// <remarks/>
        public void eodReportAsync(string session_key, string content, string backref, object userState) {
            if ((this.eodReportOperationCompleted == null)) {
                this.eodReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OneodReportOperationCompleted);
            }
            this.InvokeAsync("eodReport", new object[] {
                        session_key,
                        content,
                        backref}, this.eodReportOperationCompleted, userState);
        }
        
        private void OneodReportOperationCompleted(object arg) {
            if ((this.eodReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eodReportCompleted(this, new eodReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void authenticateCompletedEventHandler(object sender, authenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void verifyReferenceCompletedEventHandler(object sender, verifyReferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyReferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyReferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void transactCompletedEventHandler(object sender, transactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void closeTransactionCompletedEventHandler(object sender, closeTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class closeTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal closeTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void eodReportCompletedEventHandler(object sender, eodReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eodReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eodReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591