//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UtilReqSender.StarTimes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IHaiWaiElectronicPaymentServiceHttpBinding", Namespace="http://service.haiwai.sms.star.com")]
    public partial class IHaiWaiElectronicPaymentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback customerPay2OperationCompleted;
        
        private System.Threading.SendOrPostCallback rechargeAndMultiChangeProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechargeAndChangeProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback querySubscriberInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback customerPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateAndQuerySubscriberInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IHaiWaiElectronicPaymentService() {
            this.Url = global::UtilReqSender.Properties.Settings.Default.UtilReqSender_StarTimes_IHaiWaiElectronicPaymentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event customerPay2CompletedEventHandler customerPay2Completed;
        
        /// <remarks/>
        public event rechargeAndMultiChangeProductCompletedEventHandler rechargeAndMultiChangeProductCompleted;
        
        /// <remarks/>
        public event rechargeAndChangeProductCompletedEventHandler rechargeAndChangeProductCompleted;
        
        /// <remarks/>
        public event queryBalanceCompletedEventHandler queryBalanceCompleted;
        
        /// <remarks/>
        public event querySubscriberInfoCompletedEventHandler querySubscriberInfoCompleted;
        
        /// <remarks/>
        public event customerPayCompletedEventHandler customerPayCompleted;
        
        /// <remarks/>
        public event validateAndQuerySubscriberInfoCompletedEventHandler validateAndQuerySubscriberInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.haiwai.sms.star.com", ResponseNamespace="http://service.haiwai.sms.star.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public CustomerPayResult2 customerPay2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CustomerPayDto2 in0) {
            object[] results = this.Invoke("customerPay2", new object[] {
                        in0});
            return ((CustomerPayResult2)(results[0]));
        }
        
        /// <remarks/>
        public void customerPay2Async(CustomerPayDto2 in0) {
            this.customerPay2Async(in0, null);
        }
        
        /// <remarks/>
        public void customerPay2Async(CustomerPayDto2 in0, object userState) {
            if ((this.customerPay2OperationCompleted == null)) {
                this.customerPay2OperationCompleted = new System.Threading.SendOrPostCallback(this.OncustomerPay2OperationCompleted);
            }
            this.InvokeAsync("customerPay2", new object[] {
                        in0}, this.customerPay2OperationCompleted, userState);
        }
        
        private void OncustomerPay2OperationCompleted(object arg) {
            if ((this.customerPay2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.customerPay2Completed(this, new customerPay2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.haiwai.sms.star.com", ResponseNamespace="http://service.haiwai.sms.star.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public USSDApiResponse rechargeAndMultiChangeProduct([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<double> in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6) {
            object[] results = this.Invoke("rechargeAndMultiChangeProduct", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6});
            return ((USSDApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void rechargeAndMultiChangeProductAsync(string in0, string in1, System.Nullable<double> in2, string in3, string in4, string in5, string in6) {
            this.rechargeAndMultiChangeProductAsync(in0, in1, in2, in3, in4, in5, in6, null);
        }
        
        /// <remarks/>
        public void rechargeAndMultiChangeProductAsync(string in0, string in1, System.Nullable<double> in2, string in3, string in4, string in5, string in6, object userState) {
            if ((this.rechargeAndMultiChangeProductOperationCompleted == null)) {
                this.rechargeAndMultiChangeProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechargeAndMultiChangeProductOperationCompleted);
            }
            this.InvokeAsync("rechargeAndMultiChangeProduct", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6}, this.rechargeAndMultiChangeProductOperationCompleted, userState);
        }
        
        private void OnrechargeAndMultiChangeProductOperationCompleted(object arg) {
            if ((this.rechargeAndMultiChangeProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechargeAndMultiChangeProductCompleted(this, new rechargeAndMultiChangeProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.haiwai.sms.star.com", ResponseNamespace="http://service.haiwai.sms.star.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public ThirdPartnerRes rechargeAndChangeProduct([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RechargeAndChangeProductCondition in0) {
            object[] results = this.Invoke("rechargeAndChangeProduct", new object[] {
                        in0});
            return ((ThirdPartnerRes)(results[0]));
        }
        
        /// <remarks/>
        public void rechargeAndChangeProductAsync(RechargeAndChangeProductCondition in0) {
            this.rechargeAndChangeProductAsync(in0, null);
        }
        
        /// <remarks/>
        public void rechargeAndChangeProductAsync(RechargeAndChangeProductCondition in0, object userState) {
            if ((this.rechargeAndChangeProductOperationCompleted == null)) {
                this.rechargeAndChangeProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechargeAndChangeProductOperationCompleted);
            }
            this.InvokeAsync("rechargeAndChangeProduct", new object[] {
                        in0}, this.rechargeAndChangeProductOperationCompleted, userState);
        }
        
        private void OnrechargeAndChangeProductOperationCompleted(object arg) {
            if ((this.rechargeAndChangeProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechargeAndChangeProductCompleted(this, new rechargeAndChangeProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.haiwai.sms.star.com", ResponseNamespace="http://service.haiwai.sms.star.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public BalanceInfo queryBalance([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string transactionNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string payerID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string payerPwd, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string customerCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string smartCardCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string customerPwd, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceType) {
            object[] results = this.Invoke("queryBalance", new object[] {
                        transactionNo,
                        payerID,
                        payerPwd,
                        customerCode,
                        smartCardCode,
                        customerPwd,
                        deviceType});
            return ((BalanceInfo)(results[0]));
        }
        
        /// <remarks/>
        public void queryBalanceAsync(string transactionNo, string payerID, string payerPwd, string customerCode, string smartCardCode, string customerPwd, string deviceType) {
            this.queryBalanceAsync(transactionNo, payerID, payerPwd, customerCode, smartCardCode, customerPwd, deviceType, null);
        }
        
        /// <remarks/>
        public void queryBalanceAsync(string transactionNo, string payerID, string payerPwd, string customerCode, string smartCardCode, string customerPwd, string deviceType, object userState) {
            if ((this.queryBalanceOperationCompleted == null)) {
                this.queryBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryBalanceOperationCompleted);
            }
            this.InvokeAsync("queryBalance", new object[] {
                        transactionNo,
                        payerID,
                        payerPwd,
                        customerCode,
                        smartCardCode,
                        customerPwd,
                        deviceType}, this.queryBalanceOperationCompleted, userState);
        }
        
        private void OnqueryBalanceOperationCompleted(object arg) {
            if ((this.queryBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryBalanceCompleted(this, new queryBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.haiwai.sms.star.com", ResponseNamespace="http://service.haiwai.sms.star.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public SubscriberQueryResult querySubscriberInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SubscriberQueryCondition in0) {
            object[] results = this.Invoke("querySubscriberInfo", new object[] {
                        in0});
            return ((SubscriberQueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void querySubscriberInfoAsync(SubscriberQueryCondition in0) {
            this.querySubscriberInfoAsync(in0, null);
        }
        
        /// <remarks/>
        public void querySubscriberInfoAsync(SubscriberQueryCondition in0, object userState) {
            if ((this.querySubscriberInfoOperationCompleted == null)) {
                this.querySubscriberInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnquerySubscriberInfoOperationCompleted);
            }
            this.InvokeAsync("querySubscriberInfo", new object[] {
                        in0}, this.querySubscriberInfoOperationCompleted, userState);
        }
        
        private void OnquerySubscriberInfoOperationCompleted(object arg) {
            if ((this.querySubscriberInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.querySubscriberInfoCompleted(this, new querySubscriberInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.haiwai.sms.star.com", ResponseNamespace="http://service.haiwai.sms.star.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public CustomerPayResult customerPay([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string transactionNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string payerID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string payerPwd, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string customerCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string customerName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string customerTel, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string smartCardCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<double> fee, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string receiptCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string transferTime) {
            object[] results = this.Invoke("customerPay", new object[] {
                        transactionNo,
                        payerID,
                        payerPwd,
                        customerCode,
                        customerName,
                        customerTel,
                        smartCardCode,
                        fee,
                        receiptCode,
                        deviceType,
                        transferTime});
            return ((CustomerPayResult)(results[0]));
        }
        
        /// <remarks/>
        public void customerPayAsync(string transactionNo, string payerID, string payerPwd, string customerCode, string customerName, string customerTel, string smartCardCode, System.Nullable<double> fee, string receiptCode, string deviceType, string transferTime) {
            this.customerPayAsync(transactionNo, payerID, payerPwd, customerCode, customerName, customerTel, smartCardCode, fee, receiptCode, deviceType, transferTime, null);
        }
        
        /// <remarks/>
        public void customerPayAsync(string transactionNo, string payerID, string payerPwd, string customerCode, string customerName, string customerTel, string smartCardCode, System.Nullable<double> fee, string receiptCode, string deviceType, string transferTime, object userState) {
            if ((this.customerPayOperationCompleted == null)) {
                this.customerPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OncustomerPayOperationCompleted);
            }
            this.InvokeAsync("customerPay", new object[] {
                        transactionNo,
                        payerID,
                        payerPwd,
                        customerCode,
                        customerName,
                        customerTel,
                        smartCardCode,
                        fee,
                        receiptCode,
                        deviceType,
                        transferTime}, this.customerPayOperationCompleted, userState);
        }
        
        private void OncustomerPayOperationCompleted(object arg) {
            if ((this.customerPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.customerPayCompleted(this, new customerPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.haiwai.sms.star.com", ResponseNamespace="http://service.haiwai.sms.star.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public USSDApiResponse validateAndQuerySubscriberInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("validateAndQuerySubscriberInfo", new object[] {
                        in0,
                        in1,
                        in2});
            return ((USSDApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void validateAndQuerySubscriberInfoAsync(string in0, string in1, string in2) {
            this.validateAndQuerySubscriberInfoAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void validateAndQuerySubscriberInfoAsync(string in0, string in1, string in2, object userState) {
            if ((this.validateAndQuerySubscriberInfoOperationCompleted == null)) {
                this.validateAndQuerySubscriberInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateAndQuerySubscriberInfoOperationCompleted);
            }
            this.InvokeAsync("validateAndQuerySubscriberInfo", new object[] {
                        in0,
                        in1,
                        in2}, this.validateAndQuerySubscriberInfoOperationCompleted, userState);
        }
        
        private void OnvalidateAndQuerySubscriberInfoOperationCompleted(object arg) {
            if ((this.validateAndQuerySubscriberInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateAndQuerySubscriberInfoCompleted(this, new validateAndQuerySubscriberInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://haiwai.model.sms.star.com")]
    public partial class CustomerPayDto2 {
        
        private string customerCodeField;
        
        private string customerNameField;
        
        private string customerTelField;
        
        private string deviceTypeField;
        
        private string emailField;
        
        private System.Nullable<double> feeField;
        
        private bool feeFieldSpecified;
        
        private string payerIDField;
        
        private string payerPwdField;
        
        private string receiptCodeField;
        
        private string smartCardCodeField;
        
        private string transactionNoField;
        
        private string transferTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerTel {
            get {
                return this.customerTelField;
            }
            set {
                this.customerTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string payerID {
            get {
                return this.payerIDField;
            }
            set {
                this.payerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string payerPwd {
            get {
                return this.payerPwdField;
            }
            set {
                this.payerPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string receiptCode {
            get {
                return this.receiptCodeField;
            }
            set {
                this.receiptCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string smartCardCode {
            get {
                return this.smartCardCodeField;
            }
            set {
                this.smartCardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionNo {
            get {
                return this.transactionNoField;
            }
            set {
                this.transactionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transferTime {
            get {
                return this.transferTimeField;
            }
            set {
                this.transferTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://condition.haiwai.model.sms.star.com")]
    public partial class SubscriberQueryCondition {
        
        private string payerIDField;
        
        private string payerPwdField;
        
        private string smartCardCodeField;
        
        private string transactionNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string payerID {
            get {
                return this.payerIDField;
            }
            set {
                this.payerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string payerPwd {
            get {
                return this.payerPwdField;
            }
            set {
                this.payerPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string smartCardCode {
            get {
                return this.smartCardCodeField;
            }
            set {
                this.smartCardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionNo {
            get {
                return this.transactionNoField;
            }
            set {
                this.transactionNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://condition.haiwai.model.sms.star.com")]
    public partial class RechargeAndChangeProductCondition {
        
        private System.Nullable<double> feeField;
        
        private bool feeFieldSpecified;
        
        private string payerIDField;
        
        private string payerPwdField;
        
        private string productNoField;
        
        private string smartCardCodeField;
        
        private string transactionNoField;
        
        private string transferTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string payerID {
            get {
                return this.payerIDField;
            }
            set {
                this.payerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string payerPwd {
            get {
                return this.payerPwdField;
            }
            set {
                this.payerPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productNo {
            get {
                return this.productNoField;
            }
            set {
                this.productNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string smartCardCode {
            get {
                return this.smartCardCodeField;
            }
            set {
                this.smartCardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionNo {
            get {
                return this.transactionNoField;
            }
            set {
                this.transactionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transferTime {
            get {
                return this.transferTimeField;
            }
            set {
                this.transferTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://haiwai.model.sms.star.com")]
    public partial class ProductInfo {
        
        private string productDescField;
        
        private string productNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productDesc {
            get {
                return this.productDescField;
            }
            set {
                this.productDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productNo {
            get {
                return this.productNoField;
            }
            set {
                this.productNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://haiwai.model.sms.star.com")]
    public partial class SubscriberQueryResult {
        
        private System.Nullable<double> balanceField;
        
        private bool balanceFieldSpecified;
        
        private ProductInfo[] canOrderProductInfosField;
        
        private string customerNameField;
        
        private string orderedProductsDescField;
        
        private string returnCodeField;
        
        private string returnMsgField;
        
        private string smartCardCodeField;
        
        private System.Nullable<int> subscriberStatusField;
        
        private bool subscriberStatusFieldSpecified;
        
        private string transactionlNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool balanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ProductInfo[] canOrderProductInfos {
            get {
                return this.canOrderProductInfosField;
            }
            set {
                this.canOrderProductInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderedProductsDesc {
            get {
                return this.orderedProductsDescField;
            }
            set {
                this.orderedProductsDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnMsg {
            get {
                return this.returnMsgField;
            }
            set {
                this.returnMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string smartCardCode {
            get {
                return this.smartCardCodeField;
            }
            set {
                this.smartCardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> subscriberStatus {
            get {
                return this.subscriberStatusField;
            }
            set {
                this.subscriberStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subscriberStatusSpecified {
            get {
                return this.subscriberStatusFieldSpecified;
            }
            set {
                this.subscriberStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionlNo {
            get {
                return this.transactionlNoField;
            }
            set {
                this.transactionlNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://haiwai.model.sms.star.com")]
    public partial class ThirdPartnerRes {
        
        private string returnCodeField;
        
        private string returnMsgField;
        
        private string transactionlNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnMsg {
            get {
                return this.returnMsgField;
            }
            set {
                this.returnMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionlNo {
            get {
                return this.transactionlNoField;
            }
            set {
                this.transactionlNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.service.sms.star.com")]
    public partial class CustomerPayResult {
        
        private string tELDealIDField;
        
        private System.Nullable<double> balanceField;
        
        private bool balanceFieldSpecified;
        
        private string customerCodeField;
        
        private string customerContectTelField;
        
        private string customerNameField;
        
        private System.Nullable<double> feeField;
        
        private bool feeFieldSpecified;
        
        private string orderCodeField;
        
        private string returnCodeField;
        
        private string returnMsgField;
        
        private string smartCardCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TELDealID {
            get {
                return this.tELDealIDField;
            }
            set {
                this.tELDealIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool balanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerContectTel {
            get {
                return this.customerContectTelField;
            }
            set {
                this.customerContectTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderCode {
            get {
                return this.orderCodeField;
            }
            set {
                this.orderCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnMsg {
            get {
                return this.returnMsgField;
            }
            set {
                this.returnMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string smartCardCode {
            get {
                return this.smartCardCodeField;
            }
            set {
                this.smartCardCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.service.sms.star.com")]
    public partial class BalanceInfo {
        
        private string tELDealIDField;
        
        private System.Nullable<double> balanceField;
        
        private bool balanceFieldSpecified;
        
        private System.Nullable<double> billAmountField;
        
        private bool billAmountFieldSpecified;
        
        private string customerCodeField;
        
        private string customerNameField;
        
        private System.Nullable<int> payTypeField;
        
        private bool payTypeFieldSpecified;
        
        private string returnCodeField;
        
        private string returnMsgField;
        
        private string smartCardCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TELDealID {
            get {
                return this.tELDealIDField;
            }
            set {
                this.tELDealIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool balanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> billAmount {
            get {
                return this.billAmountField;
            }
            set {
                this.billAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool billAmountSpecified {
            get {
                return this.billAmountFieldSpecified;
            }
            set {
                this.billAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> payType {
            get {
                return this.payTypeField;
            }
            set {
                this.payTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool payTypeSpecified {
            get {
                return this.payTypeFieldSpecified;
            }
            set {
                this.payTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnMsg {
            get {
                return this.returnMsgField;
            }
            set {
                this.returnMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string smartCardCode {
            get {
                return this.smartCardCodeField;
            }
            set {
                this.smartCardCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.beans.crm.com")]
    public partial class USSDApiResponse {
        
        private object dataField;
        
        private string errormessageField;
        
        private string resultcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errormessage {
            get {
                return this.errormessageField;
            }
            set {
                this.errormessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resultcode {
            get {
                return this.resultcodeField;
            }
            set {
                this.resultcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://haiwai.model.sms.star.com")]
    public partial class CustomerPayResult2 {
        
        private string orderCodeField;
        
        private string returnCodeField;
        
        private string returnMsgField;
        
        private string transactionlNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderCode {
            get {
                return this.orderCodeField;
            }
            set {
                this.orderCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnMsg {
            get {
                return this.returnMsgField;
            }
            set {
                this.returnMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionlNo {
            get {
                return this.transactionlNoField;
            }
            set {
                this.transactionlNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void customerPay2CompletedEventHandler(object sender, customerPay2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class customerPay2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal customerPay2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerPayResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerPayResult2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void rechargeAndMultiChangeProductCompletedEventHandler(object sender, rechargeAndMultiChangeProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechargeAndMultiChangeProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechargeAndMultiChangeProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USSDApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USSDApiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void rechargeAndChangeProductCompletedEventHandler(object sender, rechargeAndChangeProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechargeAndChangeProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechargeAndChangeProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThirdPartnerRes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThirdPartnerRes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void queryBalanceCompletedEventHandler(object sender, queryBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BalanceInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BalanceInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void querySubscriberInfoCompletedEventHandler(object sender, querySubscriberInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class querySubscriberInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal querySubscriberInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberQueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberQueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void customerPayCompletedEventHandler(object sender, customerPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class customerPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal customerPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerPayResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerPayResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void validateAndQuerySubscriberInfoCompletedEventHandler(object sender, validateAndQuerySubscriberInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateAndQuerySubscriberInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateAndQuerySubscriberInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USSDApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USSDApiResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591