//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UtilityReferences.PBU {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CardlessMoMoApiSoap", Namespace="http://CardlessMoMoApi/")]
    public partial class CardlessMoMoApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MoMoTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostTransactionToUtilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback InquireUtilityCustomerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CardlessMoMoApi() {
            this.Url = global::UtilityReferences.Properties.Settings.Default.UtilityReferences_PBU_CardlessMoMoApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MoMoTransferCompletedEventHandler MoMoTransferCompleted;
        
        /// <remarks/>
        public event PostTransactionToUtilityCompletedEventHandler PostTransactionToUtilityCompleted;
        
        /// <remarks/>
        public event InquireUtilityCustomerCompletedEventHandler InquireUtilityCustomerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CardlessMoMoApi/MoMoTransfer", RequestNamespace="http://CardlessMoMoApi/", ResponseNamespace="http://CardlessMoMoApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response MoMoTransfer(Transaction trans) {
            object[] results = this.Invoke("MoMoTransfer", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void MoMoTransferAsync(Transaction trans) {
            this.MoMoTransferAsync(trans, null);
        }
        
        /// <remarks/>
        public void MoMoTransferAsync(Transaction trans, object userState) {
            if ((this.MoMoTransferOperationCompleted == null)) {
                this.MoMoTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoMoTransferOperationCompleted);
            }
            this.InvokeAsync("MoMoTransfer", new object[] {
                        trans}, this.MoMoTransferOperationCompleted, userState);
        }
        
        private void OnMoMoTransferOperationCompleted(object arg) {
            if ((this.MoMoTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoMoTransferCompleted(this, new MoMoTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CardlessMoMoApi/PostTransactionToUtility", RequestNamespace="http://CardlessMoMoApi/", ResponseNamespace="http://CardlessMoMoApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostTransactionToUtility(UtilityTransaction trans) {
            object[] results = this.Invoke("PostTransactionToUtility", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostTransactionToUtilityAsync(UtilityTransaction trans) {
            this.PostTransactionToUtilityAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostTransactionToUtilityAsync(UtilityTransaction trans, object userState) {
            if ((this.PostTransactionToUtilityOperationCompleted == null)) {
                this.PostTransactionToUtilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostTransactionToUtilityOperationCompleted);
            }
            this.InvokeAsync("PostTransactionToUtility", new object[] {
                        trans}, this.PostTransactionToUtilityOperationCompleted, userState);
        }
        
        private void OnPostTransactionToUtilityOperationCompleted(object arg) {
            if ((this.PostTransactionToUtilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostTransactionToUtilityCompleted(this, new PostTransactionToUtilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CardlessMoMoApi/InquireUtilityCustomer", RequestNamespace="http://CardlessMoMoApi/", ResponseNamespace="http://CardlessMoMoApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer InquireUtilityCustomer(string utilityCode, string CustRef, string area, string VendorCode, string Password) {
            object[] results = this.Invoke("InquireUtilityCustomer", new object[] {
                        utilityCode,
                        CustRef,
                        area,
                        VendorCode,
                        Password});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void InquireUtilityCustomerAsync(string utilityCode, string CustRef, string area, string VendorCode, string Password) {
            this.InquireUtilityCustomerAsync(utilityCode, CustRef, area, VendorCode, Password, null);
        }
        
        /// <remarks/>
        public void InquireUtilityCustomerAsync(string utilityCode, string CustRef, string area, string VendorCode, string Password, object userState) {
            if ((this.InquireUtilityCustomerOperationCompleted == null)) {
                this.InquireUtilityCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInquireUtilityCustomerOperationCompleted);
            }
            this.InvokeAsync("InquireUtilityCustomer", new object[] {
                        utilityCode,
                        CustRef,
                        area,
                        VendorCode,
                        Password}, this.InquireUtilityCustomerOperationCompleted, userState);
        }
        
        private void OnInquireUtilityCustomerOperationCompleted(object arg) {
            if ((this.InquireUtilityCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InquireUtilityCustomerCompleted(this, new InquireUtilityCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CardlessMoMoApi/")]
    public partial class Transaction {
        
        private string bankCodeField;
        
        private string recipientTelNumberField;
        
        private string digitalSignatureField;
        
        private string tranTypeField;
        
        private string passwordField;
        
        private string vendorCodeField;
        
        private string paymentDateField;
        
        private string customerNameField;
        
        private string customerRefField;
        
        private string collectionAreaField;
        
        private string collectionBranchField;
        
        private string channelField;
        
        private string fromTelephoneField;
        
        private string fromAccountField;
        
        private string toAccountField;
        
        private string toTelephoneField;
        
        private string transactionAmountField;
        
        private string narrationField;
        
        private string tellerField;
        
        /// <remarks/>
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientTelNumber {
            get {
                return this.recipientTelNumberField;
            }
            set {
                this.recipientTelNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DigitalSignature {
            get {
                return this.digitalSignatureField;
            }
            set {
                this.digitalSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string TranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string VendorCode {
            get {
                return this.vendorCodeField;
            }
            set {
                this.vendorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerRef {
            get {
                return this.customerRefField;
            }
            set {
                this.customerRefField = value;
            }
        }
        
        /// <remarks/>
        public string collectionArea {
            get {
                return this.collectionAreaField;
            }
            set {
                this.collectionAreaField = value;
            }
        }
        
        /// <remarks/>
        public string collectionBranch {
            get {
                return this.collectionBranchField;
            }
            set {
                this.collectionBranchField = value;
            }
        }
        
        /// <remarks/>
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string FromTelephone {
            get {
                return this.fromTelephoneField;
            }
            set {
                this.fromTelephoneField = value;
            }
        }
        
        /// <remarks/>
        public string FromAccount {
            get {
                return this.fromAccountField;
            }
            set {
                this.fromAccountField = value;
            }
        }
        
        /// <remarks/>
        public string ToAccount {
            get {
                return this.toAccountField;
            }
            set {
                this.toAccountField = value;
            }
        }
        
        /// <remarks/>
        public string ToTelephone {
            get {
                return this.toTelephoneField;
            }
            set {
                this.toTelephoneField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        public string Narration {
            get {
                return this.narrationField;
            }
            set {
                this.narrationField = value;
            }
        }
        
        /// <remarks/>
        public string Teller {
            get {
                return this.tellerField;
            }
            set {
                this.tellerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CardlessMoMoApi/")]
    public partial class Customer {
        
        private string areaField;
        
        private string outStandingBalField;
        
        private string statusDescriptionField;
        
        private string statusCodeField;
        
        private string custRefField;
        
        private string custNameField;
        
        private string customerTypeField;
        
        /// <remarks/>
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        public string OutStandingBal {
            get {
                return this.outStandingBalField;
            }
            set {
                this.outStandingBalField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustRef {
            get {
                return this.custRefField;
            }
            set {
                this.custRefField = value;
            }
        }
        
        /// <remarks/>
        public string CustName {
            get {
                return this.custNameField;
            }
            set {
                this.custNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CardlessMoMoApi/")]
    public partial class UtilityTransaction {
        
        private string custRefField;
        
        private string areaField;
        
        private string digitalSignatureField;
        
        private string channelField;
        
        private string vendorCodeField;
        
        private string custTypeField;
        
        private string custNameField;
        
        private string customerTelField;
        
        private string vendorTransactionRefField;
        
        private string fromAccountField;
        
        private string tellerField;
        
        private string reversalField;
        
        private string paymentDateField;
        
        private string transactionAmountField;
        
        private string paymentTypeField;
        
        private string transactionChargeField;
        
        private string emailField;
        
        private string transactionTypeField;
        
        private string collectionAreaField;
        
        private string collectionBranchField;
        
        private string narrationField;
        
        private string utilityCodeField;
        
        private string passwordField;
        
        /// <remarks/>
        public string CustRef {
            get {
                return this.custRefField;
            }
            set {
                this.custRefField = value;
            }
        }
        
        /// <remarks/>
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        public string DigitalSignature {
            get {
                return this.digitalSignatureField;
            }
            set {
                this.digitalSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string VendorCode {
            get {
                return this.vendorCodeField;
            }
            set {
                this.vendorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustType {
            get {
                return this.custTypeField;
            }
            set {
                this.custTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CustName {
            get {
                return this.custNameField;
            }
            set {
                this.custNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerTel {
            get {
                return this.customerTelField;
            }
            set {
                this.customerTelField = value;
            }
        }
        
        /// <remarks/>
        public string VendorTransactionRef {
            get {
                return this.vendorTransactionRefField;
            }
            set {
                this.vendorTransactionRefField = value;
            }
        }
        
        /// <remarks/>
        public string FromAccount {
            get {
                return this.fromAccountField;
            }
            set {
                this.fromAccountField = value;
            }
        }
        
        /// <remarks/>
        public string Teller {
            get {
                return this.tellerField;
            }
            set {
                this.tellerField = value;
            }
        }
        
        /// <remarks/>
        public string Reversal {
            get {
                return this.reversalField;
            }
            set {
                this.reversalField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionCharge {
            get {
                return this.transactionChargeField;
            }
            set {
                this.transactionChargeField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionArea {
            get {
                return this.collectionAreaField;
            }
            set {
                this.collectionAreaField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionBranch {
            get {
                return this.collectionBranchField;
            }
            set {
                this.collectionBranchField = value;
            }
        }
        
        /// <remarks/>
        public string Narration {
            get {
                return this.narrationField;
            }
            set {
                this.narrationField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityCode {
            get {
                return this.utilityCodeField;
            }
            set {
                this.utilityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CardlessMoMoApi/")]
    public partial class Response {
        
        private string pegPayPostIdField;
        
        private string transactionIdField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public string PegPayPostId {
            get {
                return this.pegPayPostIdField;
            }
            set {
                this.pegPayPostIdField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MoMoTransferCompletedEventHandler(object sender, MoMoTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoMoTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoMoTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PostTransactionToUtilityCompletedEventHandler(object sender, PostTransactionToUtilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostTransactionToUtilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostTransactionToUtilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void InquireUtilityCustomerCompletedEventHandler(object sender, InquireUtilityCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InquireUtilityCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InquireUtilityCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591