//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UtilityReferences.SchoolsApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SchoolApiSoap", Namespace="SchoolApi/")]
    public partial class SchoolApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateSchoolCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostOnlinePaymentForProcessingOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakePaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReconcileSingleTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReconcileTransactionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SchoolApi() {
            this.Url = global::UtilityReferences.Properties.Settings.Default.UtilityReferences_SchoolsApi_SchoolApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateSchoolCodeCompletedEventHandler ValidateSchoolCodeCompleted;
        
        /// <remarks/>
        public event GetStudentCompletedEventHandler GetStudentCompleted;
        
        /// <remarks/>
        public event PostOnlinePaymentForProcessingCompletedEventHandler PostOnlinePaymentForProcessingCompleted;
        
        /// <remarks/>
        public event MakePaymentCompletedEventHandler MakePaymentCompleted;
        
        /// <remarks/>
        public event IsValidTransactionCompletedEventHandler IsValidTransactionCompleted;
        
        /// <remarks/>
        public event GetTransactionStatusCompletedEventHandler GetTransactionStatusCompleted;
        
        /// <remarks/>
        public event ReconcileSingleTransactionCompletedEventHandler ReconcileSingleTransactionCompleted;
        
        /// <remarks/>
        public event ReconcileTransactionsCompletedEventHandler ReconcileTransactionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SchoolApi/ValidateSchoolCode", RequestNamespace="SchoolApi/", ResponseNamespace="SchoolApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse ValidateSchoolCode(string schoolcode) {
            object[] results = this.Invoke("ValidateSchoolCode", new object[] {
                        schoolcode});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateSchoolCodeAsync(string schoolcode) {
            this.ValidateSchoolCodeAsync(schoolcode, null);
        }
        
        /// <remarks/>
        public void ValidateSchoolCodeAsync(string schoolcode, object userState) {
            if ((this.ValidateSchoolCodeOperationCompleted == null)) {
                this.ValidateSchoolCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateSchoolCodeOperationCompleted);
            }
            this.InvokeAsync("ValidateSchoolCode", new object[] {
                        schoolcode}, this.ValidateSchoolCodeOperationCompleted, userState);
        }
        
        private void OnValidateSchoolCodeOperationCompleted(object arg) {
            if ((this.ValidateSchoolCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateSchoolCodeCompleted(this, new ValidateSchoolCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SchoolApi/GetStudent", RequestNamespace="SchoolApi/", ResponseNamespace="SchoolApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse GetStudent(string studentnumber, string schoolcode, string username, string password) {
            object[] results = this.Invoke("GetStudent", new object[] {
                        studentnumber,
                        schoolcode,
                        username,
                        password});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentAsync(string studentnumber, string schoolcode, string username, string password) {
            this.GetStudentAsync(studentnumber, schoolcode, username, password, null);
        }
        
        /// <remarks/>
        public void GetStudentAsync(string studentnumber, string schoolcode, string username, string password, object userState) {
            if ((this.GetStudentOperationCompleted == null)) {
                this.GetStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentOperationCompleted);
            }
            this.InvokeAsync("GetStudent", new object[] {
                        studentnumber,
                        schoolcode,
                        username,
                        password}, this.GetStudentOperationCompleted, userState);
        }
        
        private void OnGetStudentOperationCompleted(object arg) {
            if ((this.GetStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentCompleted(this, new GetStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SchoolApi/PostOnlinePaymentForProcessing", RequestNamespace="SchoolApi/", ResponseNamespace="SchoolApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse PostOnlinePaymentForProcessing(SchoolTransaction trans) {
            object[] results = this.Invoke("PostOnlinePaymentForProcessing", new object[] {
                        trans});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PostOnlinePaymentForProcessingAsync(SchoolTransaction trans) {
            this.PostOnlinePaymentForProcessingAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostOnlinePaymentForProcessingAsync(SchoolTransaction trans, object userState) {
            if ((this.PostOnlinePaymentForProcessingOperationCompleted == null)) {
                this.PostOnlinePaymentForProcessingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostOnlinePaymentForProcessingOperationCompleted);
            }
            this.InvokeAsync("PostOnlinePaymentForProcessing", new object[] {
                        trans}, this.PostOnlinePaymentForProcessingOperationCompleted, userState);
        }
        
        private void OnPostOnlinePaymentForProcessingOperationCompleted(object arg) {
            if ((this.PostOnlinePaymentForProcessingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostOnlinePaymentForProcessingCompleted(this, new PostOnlinePaymentForProcessingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SchoolApi/MakePayment", RequestNamespace="SchoolApi/", ResponseNamespace="SchoolApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse MakePayment(SchoolTransaction transaction) {
            object[] results = this.Invoke("MakePayment", new object[] {
                        transaction});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void MakePaymentAsync(SchoolTransaction transaction) {
            this.MakePaymentAsync(transaction, null);
        }
        
        /// <remarks/>
        public void MakePaymentAsync(SchoolTransaction transaction, object userState) {
            if ((this.MakePaymentOperationCompleted == null)) {
                this.MakePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakePaymentOperationCompleted);
            }
            this.InvokeAsync("MakePayment", new object[] {
                        transaction}, this.MakePaymentOperationCompleted, userState);
        }
        
        private void OnMakePaymentOperationCompleted(object arg) {
            if ((this.MakePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakePaymentCompleted(this, new MakePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SchoolApi/IsValidTransaction", RequestNamespace="SchoolApi/", ResponseNamespace="SchoolApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse IsValidTransaction(SchoolTransaction transaction) {
            object[] results = this.Invoke("IsValidTransaction", new object[] {
                        transaction});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IsValidTransactionAsync(SchoolTransaction transaction) {
            this.IsValidTransactionAsync(transaction, null);
        }
        
        /// <remarks/>
        public void IsValidTransactionAsync(SchoolTransaction transaction, object userState) {
            if ((this.IsValidTransactionOperationCompleted == null)) {
                this.IsValidTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidTransactionOperationCompleted);
            }
            this.InvokeAsync("IsValidTransaction", new object[] {
                        transaction}, this.IsValidTransactionOperationCompleted, userState);
        }
        
        private void OnIsValidTransactionOperationCompleted(object arg) {
            if ((this.IsValidTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidTransactionCompleted(this, new IsValidTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SchoolApi/GetTransactionStatus", RequestNamespace="SchoolApi/", ResponseNamespace="SchoolApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse GetTransactionStatus(string transactionId, string username, string password) {
            object[] results = this.Invoke("GetTransactionStatus", new object[] {
                        transactionId,
                        username,
                        password});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionStatusAsync(string transactionId, string username, string password) {
            this.GetTransactionStatusAsync(transactionId, username, password, null);
        }
        
        /// <remarks/>
        public void GetTransactionStatusAsync(string transactionId, string username, string password, object userState) {
            if ((this.GetTransactionStatusOperationCompleted == null)) {
                this.GetTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("GetTransactionStatus", new object[] {
                        transactionId,
                        username,
                        password}, this.GetTransactionStatusOperationCompleted, userState);
        }
        
        private void OnGetTransactionStatusOperationCompleted(object arg) {
            if ((this.GetTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionStatusCompleted(this, new GetTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SchoolApi/ReconcileSingleTransaction", RequestNamespace="SchoolApi/", ResponseNamespace="SchoolApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse ReconcileSingleTransaction(SchoolTransaction trans) {
            object[] results = this.Invoke("ReconcileSingleTransaction", new object[] {
                        trans});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReconcileSingleTransactionAsync(SchoolTransaction trans) {
            this.ReconcileSingleTransactionAsync(trans, null);
        }
        
        /// <remarks/>
        public void ReconcileSingleTransactionAsync(SchoolTransaction trans, object userState) {
            if ((this.ReconcileSingleTransactionOperationCompleted == null)) {
                this.ReconcileSingleTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReconcileSingleTransactionOperationCompleted);
            }
            this.InvokeAsync("ReconcileSingleTransaction", new object[] {
                        trans}, this.ReconcileSingleTransactionOperationCompleted, userState);
        }
        
        private void OnReconcileSingleTransactionOperationCompleted(object arg) {
            if ((this.ReconcileSingleTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReconcileSingleTransactionCompleted(this, new ReconcileSingleTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SchoolApi/ReconcileTransactions", RequestNamespace="SchoolApi/", ResponseNamespace="SchoolApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse ReconcileTransactions(SchoolTransaction trans) {
            object[] results = this.Invoke("ReconcileTransactions", new object[] {
                        trans});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReconcileTransactionsAsync(SchoolTransaction trans) {
            this.ReconcileTransactionsAsync(trans, null);
        }
        
        /// <remarks/>
        public void ReconcileTransactionsAsync(SchoolTransaction trans, object userState) {
            if ((this.ReconcileTransactionsOperationCompleted == null)) {
                this.ReconcileTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReconcileTransactionsOperationCompleted);
            }
            this.InvokeAsync("ReconcileTransactions", new object[] {
                        trans}, this.ReconcileTransactionsOperationCompleted, userState);
        }
        
        private void OnReconcileTransactionsOperationCompleted(object arg) {
            if ((this.ReconcileTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReconcileTransactionsCompleted(this, new ReconcileTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SchoolApi/")]
    public partial class ApiResponse {
        
        private string chargeField;
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        private string receiptNumberField;
        
        private Student studentField;
        
        private ApiTransaction[] transactionsField;
        
        private SchoolFee[] schoolFeesField;
        
        private Student[] stdListField;
        
        /// <remarks/>
        public string Charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
            }
        }
        
        /// <remarks/>
        public Student Student {
            get {
                return this.studentField;
            }
            set {
                this.studentField = value;
            }
        }
        
        /// <remarks/>
        public ApiTransaction[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
            }
        }
        
        /// <remarks/>
        public SchoolFee[] SchoolFees {
            get {
                return this.schoolFeesField;
            }
            set {
                this.schoolFeesField = value;
            }
        }
        
        /// <remarks/>
        public Student[] StdList {
            get {
                return this.stdListField;
            }
            set {
                this.stdListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SchoolApi/")]
    public partial class Student {
        
        private string statusCodeField;
        
        private string bankIdField;
        
        private string responseStatusField;
        
        private string authCodeField;
        
        private string classNameField;
        
        private string bankCodeField;
        
        private string minimumPaymentField;
        
        private string schoolStatusField;
        
        private string schoolFeeField;
        
        private string schoolAccountField;
        
        private string amountToPayField;
        
        private string schoolField;
        
        private string levelField;
        
        private string stdNumberField;
        
        private string stdNameField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BankId {
            get {
                return this.bankIdField;
            }
            set {
                this.bankIdField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MinimumPayment {
            get {
                return this.minimumPaymentField;
            }
            set {
                this.minimumPaymentField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolStatus {
            get {
                return this.schoolStatusField;
            }
            set {
                this.schoolStatusField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolFee {
            get {
                return this.schoolFeeField;
            }
            set {
                this.schoolFeeField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolAccount {
            get {
                return this.schoolAccountField;
            }
            set {
                this.schoolAccountField = value;
            }
        }
        
        /// <remarks/>
        public string AmountToPay {
            get {
                return this.amountToPayField;
            }
            set {
                this.amountToPayField = value;
            }
        }
        
        /// <remarks/>
        public string School {
            get {
                return this.schoolField;
            }
            set {
                this.schoolField = value;
            }
        }
        
        /// <remarks/>
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public string StdNumber {
            get {
                return this.stdNumberField;
            }
            set {
                this.stdNumberField = value;
            }
        }
        
        /// <remarks/>
        public string StdName {
            get {
                return this.stdNameField;
            }
            set {
                this.stdNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SchoolApi/")]
    public partial class SchoolFee {
        
        private string classiField;
        
        private string feeField;
        
        /// <remarks/>
        public string Classi {
            get {
                return this.classiField;
            }
            set {
                this.classiField = value;
            }
        }
        
        /// <remarks/>
        public string Fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiTransaction))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SchoolApi/")]
    public partial class SchoolTransaction {
        
        private bool allowDirectNotificationField;
        
        private string bankCodeField;
        
        private string reversalField;
        
        private string isDirectPostField;
        
        private string isAReversalField;
        
        private string reversalIdField;
        
        private string telecomIdField;
        
        private string bankIdField;
        
        private string sendToBankField;
        
        private string sentToTelecomField;
        
        private string statusField;
        
        private string statusDescriptionField;
        
        private byte[] reconFileField;
        
        private string agentField;
        
        private string visaCvvNumberField;
        
        private string visaCardNumberField;
        
        private string schoolCodeField;
        
        private string paymentTypeField;
        
        private string transactionTypeField;
        
        private string digitalSignatureField;
        
        private string transactionIDField;
        
        private string channelField;
        
        private string studentIdField;
        
        private string studentNameField;
        
        private string amountField;
        
        private string paymentDateField;
        
        private string tellerField;
        
        private string narrationField;
        
        private string tranCharge1Field;
        
        private string tranCharge2Field;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public bool AllowDirectNotification {
            get {
                return this.allowDirectNotificationField;
            }
            set {
                this.allowDirectNotificationField = value;
            }
        }
        
        /// <remarks/>
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Reversal {
            get {
                return this.reversalField;
            }
            set {
                this.reversalField = value;
            }
        }
        
        /// <remarks/>
        public string IsDirectPost {
            get {
                return this.isDirectPostField;
            }
            set {
                this.isDirectPostField = value;
            }
        }
        
        /// <remarks/>
        public string IsAReversal {
            get {
                return this.isAReversalField;
            }
            set {
                this.isAReversalField = value;
            }
        }
        
        /// <remarks/>
        public string ReversalId {
            get {
                return this.reversalIdField;
            }
            set {
                this.reversalIdField = value;
            }
        }
        
        /// <remarks/>
        public string TelecomId {
            get {
                return this.telecomIdField;
            }
            set {
                this.telecomIdField = value;
            }
        }
        
        /// <remarks/>
        public string BankId {
            get {
                return this.bankIdField;
            }
            set {
                this.bankIdField = value;
            }
        }
        
        /// <remarks/>
        public string SendToBank {
            get {
                return this.sendToBankField;
            }
            set {
                this.sendToBankField = value;
            }
        }
        
        /// <remarks/>
        public string SentToTelecom {
            get {
                return this.sentToTelecomField;
            }
            set {
                this.sentToTelecomField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ReconFile {
            get {
                return this.reconFileField;
            }
            set {
                this.reconFileField = value;
            }
        }
        
        /// <remarks/>
        public string Agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
            }
        }
        
        /// <remarks/>
        public string VisaCvvNumber {
            get {
                return this.visaCvvNumberField;
            }
            set {
                this.visaCvvNumberField = value;
            }
        }
        
        /// <remarks/>
        public string VisaCardNumber {
            get {
                return this.visaCardNumberField;
            }
            set {
                this.visaCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolCode {
            get {
                return this.schoolCodeField;
            }
            set {
                this.schoolCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DigitalSignature {
            get {
                return this.digitalSignatureField;
            }
            set {
                this.digitalSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string StudentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
            }
        }
        
        /// <remarks/>
        public string StudentName {
            get {
                return this.studentNameField;
            }
            set {
                this.studentNameField = value;
            }
        }
        
        /// <remarks/>
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string Teller {
            get {
                return this.tellerField;
            }
            set {
                this.tellerField = value;
            }
        }
        
        /// <remarks/>
        public string Narration {
            get {
                return this.narrationField;
            }
            set {
                this.narrationField = value;
            }
        }
        
        /// <remarks/>
        public string TranCharge1 {
            get {
                return this.tranCharge1Field;
            }
            set {
                this.tranCharge1Field = value;
            }
        }
        
        /// <remarks/>
        public string TranCharge2 {
            get {
                return this.tranCharge2Field;
            }
            set {
                this.tranCharge2Field = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SchoolApi/")]
    public partial class ApiTransaction : SchoolTransaction {
        
        private string recordDateField;
        
        private string receiptNumberField;
        
        /// <remarks/>
        public string RecordDate {
            get {
                return this.recordDateField;
            }
            set {
                this.recordDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ValidateSchoolCodeCompletedEventHandler(object sender, ValidateSchoolCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateSchoolCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateSchoolCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetStudentCompletedEventHandler(object sender, GetStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PostOnlinePaymentForProcessingCompletedEventHandler(object sender, PostOnlinePaymentForProcessingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostOnlinePaymentForProcessingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostOnlinePaymentForProcessingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MakePaymentCompletedEventHandler(object sender, MakePaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void IsValidTransactionCompletedEventHandler(object sender, IsValidTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTransactionStatusCompletedEventHandler(object sender, GetTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReconcileSingleTransactionCompletedEventHandler(object sender, ReconcileSingleTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReconcileSingleTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReconcileSingleTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReconcileTransactionsCompletedEventHandler(object sender, ReconcileTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReconcileTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReconcileTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591